#!/usr/bin/python3

import sys
import time

def factorize(n):
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return f"{n}={i}*{n//i}"
    return f"{n} is a prime number"

def main(file_path):
    with open(file_path, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        result = factorize(int(number))
        print(result)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_path = sys.argv[1]

    start_time = time.time()
    main(file_path)
    end_time = time.time()

    elapsed_time = end_time - start_time
    user_time = time.process_time()
    system_time = (elapsed_time - user_time) * -1

    print(f"\nreal    {elapsed_time//60:.0f}m{elapsed_time%60:.3f}s")
    print(f"user    {user_time//60:.0f}m{user_time%60:.3f}s")
    print(f"sys     {system_time//60:.0f}m{system_time%60:.3f}s")